# 動作確認できたCMakeのバージョン
cmake_minimum_required(VERSION 3.16)

#################################################################################

include(${WORKSPACE_ROOT_DIR}/lib/cmake_hos-v4a_win32/kernel/libhosv4a.cmake)

#################################################################################

set(HOSAPLFW_DIR        "${WORKSPACE_ROOT_DIR}/lib/third_party/hos-v4a/aplfw")
set(HOSAPLFW_INC_DIR    ${HOSAPLFW_DIR} ${HOSAPLFW_DIR}/include)


#################################################################################

# --------------------------------------------------
#  Default setting
# --------------------------------------------------

# System
if(NOT LINK_SYSTEM)
    set(LINK_SYSTEM             YES)
endif()
if(NOT LINK_SYSAPI)
    set(LINK_SYSAPI             YES)
endif()
if(NOT LINK_SYSMEM)
    set(LINK_SYSMEM             YES)
endif()
if(NOT LINK_HANDLE)
    set(LINK_HANDLE             YES)
endif()
if(NOT LINK_MEMORY)
    set(LINK_MEMORY             YES)
endif()
if(NOT LINK_TIME)
    set(LINK_TIME               YES)
endif()
if(NOT LINK_PROCESS)
    set(LINK_PROCESS            YES)
endif()
if(NOT LINK_EVENT)
    set(LINK_EVENT              YES)
endif()
if(NOT LINK_FILE)
    set(LINK_FILE               YES)
endif()
if(NOT LINK_COMMAND)
    set(LINK_COMMAND            YES)
endif()

# Librarys
if(NOT LINK_VALMEMHEAP)
    set(LINK_VALMEMHEAP         YES)
endif()
if(NOT LINK_FIXMEMHEAP)
    set(LINK_FIXMEMHEAP         YES)
endif()
if(NOT LINK_AUTOMEMHEAP)
    set(LINK_AUTOMEMHEAP        YES)
endif()
if(NOT LINK_ASSOC)
    set(LINK_ASSOC              YES)
endif()
if(NOT LINK_HASHTABLE)
    set(LINK_HASHTABLE          YES)
endif()
if(NOT LINK_LIST)
    set(LINK_LIST               YES)
endif()
if(NOT LINK_STREAMBUF)
    set(LINK_STREAMBUF          YES)
endif()
if(NOT LINK_PACKETBUF)
    set(LINK_PACKETBUF          YES)
endif()
if(NOT LINK_IPCHECKSUM)
    set(LINK_IPCHECKSUM         YES)
endif()
if(NOT LINK_CRC16)
    set(LINK_CRC16              YES)
endif()
if(NOT LINK_STRINGFORMAT)
    set(LINK_STRINGFORMAT       YES)
endif()
if(NOT LINK_MEMUTIL)
    set(LINK_MEMUTIL            YES)
endif()

# Device Drivers
if(NOT LINK_VT100)
    set(LINK_VT100              YES)
endif()
if(NOT LINK_PCATTEXT)
    set(LINK_PCATTEXT           NO)
endif()
if(NOT LINK_PCATKEY)
    set(LINK_PCATKEY            NO)
endif()
if(NOT LINK_TCPIP)
    set(LINK_TCPIP              YES)
endif()
if(NOT LINK_IPETHER)
    set(LINK_IPETHER            YES)
endif()
if(NOT LINK_NE2000)
    set(LINK_NE2000             NO)
endif()
if(NOT LINK_LAN9000)
    set(LINK_LAN9000            NO)
endif()
if(NOT LINK_LAN9118)
    set(LINK_LAN9118            NO)
endif()
if(NOT LINK_PC16550)
    set(LINK_PC16550            YES)
endif()
if(NOT LINK_AT91USART)
    set(LINK_AT91USART          NO)
endif()
if(NOT LINK_RENESASSCI)
    set(LINK_RENESASSCI         NO)
endif()
if(NOT LINK_MX1UART)
    set(LINK_MX1UART            NO)
endif()
if(NOT LINK_MN103SC)
    set(LINK_MN103SC            NO)
endif()
if(NOT LINK_XILINXUARTDRV)
    set(LINK_XILINXUARTDRV      NO)
endif()
if(NOT LINK_WINSOCK)
    set(LINK_WINSOCK            NO)
endif()
if(NOT LINK_JELLYUART)
    set(LINK_JELLYUART          NO)
endif()
if(NOT LINK_I2CDRV)
    set(LINK_I2CDRV             YES)
endif()
if(NOT LINK_JELLYI2C)
    set(LINK_JELLYI2C           NO)
endif()
if(NOT LINK_FATVOL)
    set(LINK_FATVOL             YES)
endif()
if(NOT LINK_MEMDRV)
    set(LINK_MEMDRV             YES)
endif()

# Applications
if(NOT LINK_SHELL)
    set(LINK_SHELL              YES)
endif()
if(NOT LINK_WHITEBOARDCMD)
    set(LINK_WHITEBOARDCMD      YES)
endif()
if(NOT LINK_PROCESSLIST)
    set(LINK_PROCESSLIST        YES)
endif()
if(NOT LINK_PROCESSSIGNAL)
    set(LINK_PROCESSSIGNAL      YES)
endif()
if(NOT LINK_COMMANDLIST)
    set(LINK_COMMANDLIST        YES)
endif()
if(NOT LINK_MEMDUMP)
    set(LINK_MEMDUMP            YES)
endif()
if(NOT LINK_MEMWRITE)
    set(LINK_MEMWRITE           YES)
endif()
if(NOT LINK_MEMFILL)
    set(LINK_MEMFILL            YES)
endif()
if(NOT LINK_MEMCOPY)
    set(LINK_MEMCOPY            YES)
endif()
if(NOT LINK_MEMSAVE)
    set(LINK_MEMSAVE            YES)
endif()
if(NOT LINK_MEMLOAD)
    set(LINK_MEMLOAD            YES)
endif()
if(NOT LINK_MEMTEST)
    set(LINK_MEMTEST            YES)
endif()
if(NOT LINK_KEYTEST)
    set(LINK_KEYTEST            YES)
endif()
if(NOT LINK_TIMECMD)
    set(LINK_TIMECMD            YES)
endif()
if(NOT LINK_I2CCMD)
    set(LINK_I2CCMD             YES)
endif()
if(NOT LINK_FILELIST)
    set(LINK_FILELIST           YES)
endif()
if(NOT LINK_FILECAT)
    set(LINK_FILECAT            YES)
endif()
if(NOT LINK_FILECOPY)
    set(LINK_FILECOPY           YES)
endif()
if(NOT LINK_FILEDUMP)
    set(LINK_FILEDUMP           YES)
endif()
if(NOT LINK_FATMOUNT)
    set(LINK_FATMOUNT           YES)
endif()
if(NOT LINK_FLASHCMD)
    set(LINK_FLASHCMD           YES)
endif()
if(NOT LINK_ETHERSNOOP)
    set(LINK_ETHERSNOOP         YES)
endif()
if(NOT LINK_HELLO)
    set(LINK_HELLO              YES)
endif()

#################################################################################

# --------------------------------------------------
#  System
# --------------------------------------------------

# System
if(${LINK_SYSTEM})
    set(SYSTEM_DIR ${HOSAPLFW_DIR}/system/system)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${SYSTEM_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_initialize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_requestproc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_process.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_getnextprocess.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_getsystemprocess.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_lock.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/system_unlock.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/whiteboard_setstring.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/whiteboard_getstring.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/whiteboard_setinteger.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/whiteboard_getinteger.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSTEM_DIR}/whiteboard_getnextkey.c)
endif()


# System API
if(${LINK_SYSAPI})
    set(SYSAPI_DIR ${HOSAPLFW_DIR}/system/sysapi)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${SYSAPI_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysapi_initialize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysctx_isisr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysloc_lock.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysloc_unlock.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysevt_clear.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysevt_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysevt_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysevt_set.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysevt_wait.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysint_clear.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysint_disable.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysint_enable.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysisr_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysisr_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmem_alloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmem_free.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmem_getmemheap.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmem_getsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmem_realloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmtx_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmtx_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmtx_lock.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysmtx_unlock.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_start.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_terminate.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_suspend.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_resume.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_getparam.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_getcurrenthandle.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_setsignalhandler.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysprc_sendsignal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_signal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_wait.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_getsystemtime.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_systimetosecond.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_systimetonanosecond.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_getcputime.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_cputimetosecond.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/systim_cputimetonanosecond.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysio_allociomem.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/sysio_freeiomem.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSAPI_DIR}/syshos_hook.c)
endif()


# System Memory Heap
if(${LINK_SYSMEM})
    set(SYSMEM_DIR ${HOSAPLFW_DIR}/system/sysmem)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${SYSMEM_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_alignsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_alloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_free.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_getalign.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_getsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SYSMEM_DIR}/sysmemheap_realloc.c)
endif()


# Handle Object
if(${LINK_HANDLE})
    set(HANDLE_DIR ${HOSAPLFW_DIR}/system/handle)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${HANDLE_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HANDLE_DIR}/handle_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HANDLE_DIR}/handleobj_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HANDLE_DIR}/handleobj_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HANDLE_DIR}/handleobj_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HANDLE_DIR}/handleobj_destructor.c)
endif()


# Memory
if(${LINK_MEMORY})
    set(MEMORY_DIR ${HOSAPLFW_DIR}/system/memory)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMORY_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMORY_DIR}/memory.c)
endif()


# Time
if(${LINK_TIME})
    set(TIME_DIR ${HOSAPLFW_DIR}/system/time)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${TIME_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TIME_DIR}/time_getsystemtime.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TIME_DIR}/time_wait.c)
endif()


# Process
if(${LINK_PROCESS})
    set(PROCESS_DIR ${HOSAPLFW_DIR}/system/process)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PROCESS_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_createex.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getcurrenthandle.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_exit.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_waitexit.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setsignalproc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_sendsignal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getexitcode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getparam.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setparam.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_entersystemmode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_leavesystemmode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_issystemmode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setcurrentdir.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getcurrentdir.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getparentprocess.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getexecutiontime.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getcommandline.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setterminal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getterminal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setconin.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getconin.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setconout.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getconout.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setstdin.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getstdin.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setstdout.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getstdout.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_setstderr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESS_DIR}/process_getstderr.c)
endif()


# Event
if(${LINK_EVENT})
    set(EVENT_DIR ${HOSAPLFW_DIR}/system/event)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${EVENT_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${EVENT_DIR}/event_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${EVENT_DIR}/event_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${EVENT_DIR}/event_set.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${EVENT_DIR}/event_clear.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${EVENT_DIR}/event_wait.c)
endif()


# File
if(${LINK_FILE})
    set(FILE_DIR ${HOSAPLFW_DIR}/system/file)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FILE_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/console_getch.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/drvobj_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/fileobj_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/fileobj_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/fileobj_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/fileobj_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_adddevice.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_addvolume.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_removevolume.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_getvolume.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_getchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_getstring.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_initialize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_putchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_putstring.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_readdir.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_driveropen.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_relpathtoabspath.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_getdriverinformation.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_printformat.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/file_printformatv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/stdio_printformat.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncdrv_endprocess.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncdrv_sendsignal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncdrv_startprocess.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncfile_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncfile_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncfile_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncfile_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/syncfile_setsignal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvolfile_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvolfile_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvolfile_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvolfile_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_adddevice.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_removedevice.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/sysvol_getdevice.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volume_shutdown.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_shutdown.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_makedir.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILE_DIR}/volumeobj_remove.c)
endif()


# Command
if(${LINK_COMMAND})
    set(COMMAND_DIR ${HOSAPLFW_DIR}/system/command)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${COMMAND_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${COMMAND_DIR}/command.c)
endif()



# --------------------------------------------------
#  Librarys
# --------------------------------------------------

# Valiable size memory heap
if(${LINK_VALMEMHEAP})
    set(VALMEMHEAP_DIR ${HOSAPLFW_DIR}/library/container/valmemheap)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${VALMEMHEAP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_alloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_realloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_free.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_getalign.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_getsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_alignsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VALMEMHEAP_DIR}/valmemheap_ismember.c)
endif()


# Fixed size memory heap
if(${LINK_FIXMEMHEAP})
    set(FIXMEMHEAP_DIR ${HOSAPLFW_DIR}/library/container/fixmemheap)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FIXMEMHEAP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_alloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_realloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_free.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_getalign.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_getsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_alignsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FIXMEMHEAP_DIR}/fixmemheap_ismember.c)
endif()


# Auto size memory heap
if(${LINK_AUTOMEMHEAP})
    set(AUTOMEMHEAP_DIR ${HOSAPLFW_DIR}/library/container/automemheap)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${AUTOMEMHEAP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_alignsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_alloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_free.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_getalign.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_getsize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_realloc.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AUTOMEMHEAP_DIR}/automemheap_searchheap.c)
endif()


# Association Array
if(${LINK_ASSOC})
    set(ASSOC_DIR ${HOSAPLFW_DIR}/library/container/assoc)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${ASSOC_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_createex.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_add.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_set.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_get.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_getat.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_getfirst.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_getpos.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_getnext.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_remove.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_addnode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_getnode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_removenode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ASSOC_DIR}/assoc_getminnode.c)
endif()


# Hash Table
if(${LINK_HASHTABLE})
    set(HASHTABLE_DIR ${HOSAPLFW_DIR}/library/container/hashtable)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${HASHTABLE_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_createex.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_get.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_set.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_remove.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_removeall.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_findclose.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_findnext.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_findopen.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_searchnode.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HASHTABLE_DIR}/hashtable_createnode.c)
endif()


# List
if(${LINK_LIST})
    set(LIST_DIR ${HOSAPLFW_DIR}/library/container/list)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${LIST_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_createex.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_addtail.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_getat.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_getheadpos.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_getnextpos.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_getprevpos.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_gettailpos.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LIST_DIR}/list_remove.c)
endif()


# Stream Buffer
if(${LINK_STREAMBUF})
    set(STREAMBUF_DIR ${HOSAPLFW_DIR}/library/container/streambuf)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${STREAMBUF_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_getbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_sendbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_senddata.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_sendchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_recvbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_relbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_recvdata.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_recvchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_clear.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_refdatasize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STREAMBUF_DIR}/streambuf_reffreesize.c)
endif()


# Packet Buffer
if(${LINK_PACKETBUF})
    set(PACKETBUF_DIR ${HOSAPLFW_DIR}/library/container/packetbuf)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PACKETBUF_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_getbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_sendbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_senddata.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_recvbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_relbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_recvdata.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PACKETBUF_DIR}/packetbuf_clear.c)
endif()


# IP check-sum
if(${LINK_IPCHECKSUM})
    set(IPCHECKSUM_DIR ${HOSAPLFW_DIR}/library/algorithm/ipchecksum)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${IPCHECKSUM_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPCHECKSUM_DIR}/ipchecksum_getdigest.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPCHECKSUM_DIR}/ipchecksum_update.c)
endif()


# 16bit CRC
if(${LINK_CRC16})
    set(CRC16_DIR ${HOSAPLFW_DIR}/library/algorithm/crc16)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${CRC16_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${CRC16_DIR}/crc16_getdigest.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${CRC16_DIR}/crc16_update.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${CRC16_DIR}/crc16_reset.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${CRC16_DIR}/crc16_table.c)
endif()


# String Format
if(${LINK_STRINGFORMAT})
    set(STRINGFORMAT_DIR ${HOSAPLFW_DIR}/library/algorithm/stringformat)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${STRINGFORMAT_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_formatstring.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_formatstringv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_format.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_formatv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_string.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_decimal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_hexadecimal.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${STRINGFORMAT_DIR}/stringformat_nibble.c)
endif()


# Memory Operation Utility
if(${LINK_MEMUTIL})
    set(MEMUTIL_DIR ${HOSAPLFW_DIR}/library/utility/memutil)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMUTIL_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMUTIL_DIR}/memutil_memcopyb.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMUTIL_DIR}/memutil_memcopyh.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMUTIL_DIR}/memutil_memcopyw.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMUTIL_DIR}/memutil_memsetb.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMUTIL_DIR}/memutil_memseth.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMUTIL_DIR}/memutil_memsetw.c)
endif()



# --------------------------------------------------
#  Device Drivers
# --------------------------------------------------

# VT100
if(${LINK_VT100})
    set(VT100_DIR ${HOSAPLFW_DIR}/driver/console/vt100)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${VT100_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${VT100_DIR}/vt100drv_getch.c)
endif()


# PC/AT text mode screen
if(${LINK_PCATTEXT})
    set(PCATTEXT_DIR ${HOSAPLFW_DIR}/driver/console/pcattext)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PCATTEXT_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_putchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_setcursor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATTEXT_DIR}/pcattextdrv_clearscreen.c)
endif()


# PC/AT Keyboard
if(${LINK_PCATKEY})
    set(PCATKEY_DIR ${HOSAPLFW_DIR}/driver/console/pcatkey)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PCATKEY_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PCATKEY_DIR}/pcatkeydrv_flush.c)
endif()


# TCP/IP
if(${LINK_TCPIP})
    set(TCPIP_DIR ${HOSAPLFW_DIR}/driver/tcpip/tcpip)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${TCPIP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_recv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpip_stringtoaddr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpipfile_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpipfile_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpipfile_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TCPIP_DIR}/tcpipfile_destructor.c)
endif()


# IpEther
if(${LINK_IPETHER})
    set(IPETHER_DIR ${HOSAPLFW_DIR}/driver/tcpip/ipether)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${IPETHER_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_recv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${IPETHER_DIR}/ipether_getmacaddr.c)
endif()


# NE2000
if(${LINK_NE2000})
    set(NE2000_DIR ${HOSAPLFW_DIR}/driver/ether/ne2000)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${NE2000_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${NE2000_DIR}/ne2000drv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${NE2000_DIR}/ne2000hal.c)
endif()


# LAN91C111
if(${LINK_LAN9000})
    set(LAN9000_DIR ${HOSAPLFW_DIR}/driver/ether/lan9000)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${LAN9000_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_isr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000drv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_getinterruptstatus.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_getphysicaladdr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_mii.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_phyregread.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_phyregwrite.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_recv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_send.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_setinterruptmask.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_setup.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9000_DIR}/lan9000hal_stop.c)
endif()


# LAN91C111
if(${LINK_LAN9118})
    set(LAN9118_DIR ${HOSAPLFW_DIR}/driver/ether/lan9118)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${LAN9118_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${LAN9118_DIR}/lan9118drv_isr.c)
endif()


# 16550A
if(${LINK_PC16550})
    set(PC16550_DIR ${HOSAPLFW_DIR}/driver/serial/pc16550)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PC16550_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550drv_isr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_setup.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_stop.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_setspeed.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_recvchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_sendchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_enableinterrupt.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_getinterruptstatus.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PC16550_DIR}/pc16550hal_getstatus.c)
endif()


# Atmel AT91 USART
if(${LINK_AT91USART})
    set(AT91USART_DIR ${HOSAPLFW_DIR}/driver/serial/at91)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${AT91USART_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${AT91USART_DIR}/at91usartdrv_isr.c)
endif()


# Renesas SCI
if(${LINK_RENESASSCI})
    set(RENESASSCI_DIR ${HOSAPLFW_DIR}/driver/serial/renesas)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${RENESASSCI_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_isrrxerr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_isrrx.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_isrtx.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scidrv_isrtxend.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_enableinterrupt.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_recvchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_sendchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_setspeed.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_setup.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${RENESASSCI_DIR}/scihal_stop.c)
endif()


# Freescale MX1 UART
if(${LINK_MX1UART})
    set(MX1UART_DIR ${HOSAPLFW_DIR}/driver/serial/mx1)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MX1UART_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MX1UART_DIR}/mx1uartdrv_isr.c)
endif()


# Panasonic MN103 SC
if(${LINK_MN103SC})
    set(MN103SC_DIR ${HOSAPLFW_DIR}/driver/serial/mn103)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MN103SC_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_isrtx.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MN103SC_DIR}/mn103scdrv_isrrx.c)
endif()


# XILINX UART
if(${LINK_XILINXUARTDRV})
    set(XILINXUARTDRV_DIR ${HOSAPLFW_DIR}/driver/serial/xilinxuartdrv)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${XILINXUARTDRV_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${XILINXUARTDRV_DIR}/xilinxuartdrv_isr.c)
endif()


# WinSock
if(${LINK_WINSOCK})
    set(WINSOCK_DIR ${HOSAPLFW_DIR}/driver/serial/winsock)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${WINSOCK_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_close.c)
    # set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WORKSPACE_ROOT_DIR}/lib/third_party/hos-v4a_modify/aplfw/winsockdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_isr.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_read.c)
    # set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_recv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WORKSPACE_ROOT_DIR}/lib/third_party/hos-v4a_modify/aplfw/winsockdrv_recv.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_seek.c)
    # set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_send.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WORKSPACE_ROOT_DIR}/lib/third_party/hos-v4a_modify/aplfw/winsockdrv_send.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WINSOCK_DIR}/winsockdrv_write.c)
endif()


# Jelly UART
if(${LINK_JELLYUART})
    set(JELLYUART_DIR ${HOSAPLFW_DIR}/driver/serial/jelly)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${JELLYUART_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYUART_DIR}/jellyuartdrv_isr.c)
endif()


# I2C driver
if(${LINK_I2CDRV})
    set(I2CDRV_DIR ${HOSAPLFW_DIR}/driver/i2c/i2c)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${I2CDRV_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${I2CDRV_DIR}/i2cdrv_bytewrite.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${I2CDRV_DIR}/i2cdrv_byteread.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${I2CDRV_DIR}/i2cdrv_burstwrite.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${I2CDRV_DIR}/i2cdrv_burstread.c)
endif()


# Jelly I2C driver
if(${LINK_JELLYI2C})
    set(JELLYI2C_DIR ${HOSAPLFW_DIR}/driver/i2c/jelly)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${JELLYI2C_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${JELLYI2C_DIR}/jellyi2cdrv_access.c)
endif()


# FAT volume
if(${LINK_FATVOL})
    set(FATVOL_DIR ${HOSAPLFW_DIR}/driver/volume/fat)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FATVOL_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_shutdown.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_makedir.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_remove.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_clusterread.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_clusterwrite.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_flushclusterbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_flushfat.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_getclusterbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_relclusterbuf.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_alloccluster.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_freecluster.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_getnextcluster.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_setnextcluster.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatvol_syncfilesize.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatfile_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatfile_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatfile_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATVOL_DIR}/fatfile_destructor.c)
endif()


# Memory maped file driver
if(${LINK_MEMDRV})
    set(MEMDRV_DIR ${HOSAPLFW_DIR}/driver/misc/memdrv)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMDRV_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_destructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_open.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_close.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_iocontrol.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_flush.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_read.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_seek.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_write.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memdrv_getinformation.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memfile_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memfile_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memfile_constructor.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDRV_DIR}/memfile_destructor.c)
endif()



# --------------------------------------------------
#  Applications
# --------------------------------------------------

# Shell
if(${LINK_SHELL})
    set(SHELL_DIR ${HOSAPLFW_DIR}/application/syscmd/shell)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${SHELL_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_main.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_create.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_delete.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_executecommand.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_executescript.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_inputline.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_interactive.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_putchar.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_curright.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_curleft.c)
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${SHELL_DIR}/shell_replaceline.c)
endif()


# Whitboard
if(${LINK_WHITEBOARDCMD})
    set(WHITEBOARDCMD_DIR ${HOSAPLFW_DIR}/application/syscmd/whiteboardcmd)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${WHITEBOARDCMD_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${WHITEBOARDCMD_DIR}/whiteboardcmd_main.c)
endif()


# Process List
if(${LINK_PROCESSLIST})
    set(PROCESSLIST_DIR ${HOSAPLFW_DIR}/application/syscmd/processlist)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PROCESSLIST_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESSLIST_DIR}/processlist_main.c)
endif()


# Process Signal
if(${LINK_PROCESSSIGNAL})
    set(PROCESSSIGNAL_DIR ${HOSAPLFW_DIR}/application/syscmd/processsignal)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${PROCESSSIGNAL_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${PROCESSSIGNAL_DIR}/processsignal_main.c)
endif()


# Command List
if(${LINK_COMMANDLIST})
    set(COMMANDLIST_DIR ${HOSAPLFW_DIR}/application/syscmd/commandlist)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${COMMANDLIST_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${COMMANDLIST_DIR}/commandlist_main.c)
endif()


# Memory Dump
if(${LINK_MEMDUMP})
    set(MEMDUMP_DIR ${HOSAPLFW_DIR}/application/utility/memdump)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMDUMP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMDUMP_DIR}/memdump_main.c)
endif()


# Memory Write
if(${LINK_MEMWRITE})
    set(MEMWRITE_DIR ${HOSAPLFW_DIR}/application/utility/memwrite)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMWRITE_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMWRITE_DIR}/memwrite_main.c)
endif()


# Memory Fill
if(${LINK_MEMFILL})
    set(MEMFILL_DIR ${HOSAPLFW_DIR}/application/utility/memfill)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMFILL_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMFILL_DIR}/memfill_main.c)
endif()


# Memory Copy
if(${LINK_MEMCOPY})
    set(MEMCOPY_DIR ${HOSAPLFW_DIR}/application/utility/memcopy)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMCOPY_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMCOPY_DIR}/memcopy_main.c)
endif()


# Memory Save
if(${LINK_MEMSAVE})
    set(MEMSAVE_DIR ${HOSAPLFW_DIR}/application/utility/memsave)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMSAVE_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMSAVE_DIR}/memsave_main.c)
endif()


# Memory Load
if(${LINK_MEMLOAD})
    set(MEMLOAD_DIR ${HOSAPLFW_DIR}/application/utility/memload)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMLOAD_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMLOAD_DIR}/memload_main.c)
endif()


# Memory Test
if(${LINK_MEMTEST})
    set(MEMTEST_DIR ${HOSAPLFW_DIR}/application/utility/memtest)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${MEMTEST_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${MEMTEST_DIR}/memtest_main.c)
endif()


# Key Test
if(${LINK_KEYTEST})
    set(KEYTEST_DIR ${HOSAPLFW_DIR}/application/utility/keytest)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${KEYTEST_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${KEYTEST_DIR}/keytest_main.c)
endif()


# Time Command
if(${LINK_TIMECMD})
    set(TIMECMD_DIR ${HOSAPLFW_DIR}/application/utility/timecmd)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${TIMECMD_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${TIMECMD_DIR}/timecmd_main.c)
endif()


# I2C Command
if(${LINK_I2CCMD})
    set(I2CCMD_DIR ${HOSAPLFW_DIR}/application/utility/i2ccmd)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${I2CCMD_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${I2CCMD_DIR}/i2ccmd_main.c)
endif()


# File List
if(${LINK_FILELIST})
    set(FILELIST_DIR ${HOSAPLFW_DIR}/application/filecmd/filelist)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FILELIST_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILELIST_DIR}/filelist_main.c)
endif()


# File Cat
if(${LINK_FILECAT})
    set(FILECAT_DIR ${HOSAPLFW_DIR}/application/filecmd/filecat)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FILECAT_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILECAT_DIR}/filecat_main.c)
endif()


# File Copy
if(${LINK_FILECOPY})
    set(FILECOPY_DIR ${HOSAPLFW_DIR}/application/filecmd/filecopy)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FILECOPY_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILECOPY_DIR}/filecopy_main.c)
endif()


# File Dump
if(${LINK_FILEDUMP})
    set(FILEDUMP_DIR ${HOSAPLFW_DIR}/application/filecmd/filedump)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FILEDUMP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FILEDUMP_DIR}/filedump_main.c)
endif()


# FAT mount
if(${LINK_FATMOUNT})
    set(FATMOUNT_DIR ${HOSAPLFW_DIR}/application/fatcmd/fatmount)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FATMOUNT_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FATMOUNT_DIR}/fatmount_main.c)
endif()


# Flash Command
if(${LINK_FLASHCMD})
    set(FLASHCMD_DIR ${HOSAPLFW_DIR}/application/flashcmd/norflashcmd)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${FLASHCMD_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${FLASHCMD_DIR}/norflashcmd_main.c)
endif()


# Ether Snoopt
if(${LINK_ETHERSNOOP})
    set(ETHERSNOOP_DIR ${HOSAPLFW_DIR}/application/netcmd/ethersnoop)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${ETHERSNOOP_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${ETHERSNOOP_DIR}/ethersnoop_main.c)
endif()


# Hello World
if(${LINK_HELLO})
    set(HELLO_DIR ${HOSAPLFW_DIR}/application/example/hello)
    set(HOSAPLFW_INC_DIR ${HOSAPLFW_INC_DIR} ${HELLO_DIR})
    set(HOSAPLFW_SRCS ${HOSAPLFW_SRCS} ${HELLO_DIR}/hello_main.c)
endif()

#################################################################################

add_library(hosaplfw STATIC
    ${HOSAPLFW_SRCS}
)

target_include_directories(hosaplfw PRIVATE
    ${KERNEL_INC_DIR}
    ${KERNEL_INC_PROC_DIR}
    ${KERNEL_INC_IRC_DIR}
    ${HOSAPLFW_INC_DIR}
)

target_compile_options(hosaplfw
  PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/W4 /WX- /utf-8>
  PRIVATE $<$<CXX_COMPILER_ID:Clang>:-Wall -Wextra>
  PRIVATE $<$<AND:$<CXX_COMPILER_ID:Clang>,$<CONFIG:Debug>>:-g -O0>
  PRIVATE $<$<AND:$<CXX_COMPILER_ID:Clang>,$<CONFIG:Release>>:-O3 -DNDEBUG>
  PRIVATE $<$<CXX_COMPILER_ID:GNU>:-Wall>
  PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<CONFIG:Debug>>:-g -O0>
  PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<CONFIG:Release>>:-O3 -DNDEBUG>
)
