name: dev build and run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:

  build:
    strategy:
      matrix:
        lib: [vter_knl, googletest, googlemock]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Submodules
      run: |
        git config --global http.postBuffer 100M
        git submodule update --init --recursive --recommend-shallow --depth 1

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/dev/${{matrix.lib}}/ -B ${{github.workspace}}/dev/${{matrix.lib}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/dev/${{matrix.lib}}/build --config ${{env.BUILD_TYPE}}

