name: dev build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        dev_dir: ["extension/sample", "extension/sample_cli", "extension/aplfw", "extension/aplfw_cli", "googletest", "googlemock"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Submodules
      run: |
        git config --global http.postBuffer 100M
        git submodule update --init --recursive --recommend-shallow --depth 1

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/dev/${{matrix.dev_dir}}/ -B ${{github.workspace}}/dev/${{matrix.dev_dir}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D TEST_MODE=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/dev/${{matrix.dev_dir}}/build --config ${{env.BUILD_TYPE}}

