name: sample sample_win32 build (clang+ninja)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: egor-tensin/setup-clang@v1
    - uses: seanmiddleditch/gha-setup-ninja@master

    - uses: actions/checkout@v3

    - name: Checkout Submodules
      run: |
        git config --global http.postBuffer 100M
        git submodule update --init --recursive --recommend-shallow --depth 1

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/sample/sample_win32 -B ${{github.workspace}}/sample/sample_win32/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/sample/sample_win32/build --config ${{env.BUILD_TYPE}}

